# -*- coding: utf-8 -*-
"""Intro_Neural_Net_A12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-lGfnkYuIREyzELXc7MATkjC-rFH7-K
"""

import numpy as np
import matplotlib.pyplot as plt


n_bins = 4
fig, (ax0, ax1)= plt.subplots(nrows=1, ncols=1)


x = np.array([21,20,20,19,17,16,18,18,15,17])
colors = ['red', 'blue']
ax0.hist(x, n_bins, density=True, histtype='bar', color=colors, label=colors)
ax0.legend(prop={'size': 10})
ax0.set_title('Histogram of Width')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
 
# Creating dataset
salmon= np.array([21,20,19,18,18])
seabass=np.array([20,17,16,15,17])
 
# Creating histogram


plt.hist(salmon,bins = [14,16,18,20,22], 
         color = 'pink', edgecolor='black')
plt.hist(seabass,bins = [14,16,18,20,22],
         color = 'blue', edgecolor='black')

 # Adding extra features   
plt.ylabel("Number of Fish")
plt.xlabel("Width")
plt.title('Histogram of Width')
plt.legend(['Salmon','Seabass'])

# Show plot
plt.show()

salmon= np.array([3,4,5,6,7])
seabass=np.array([8,9,5,7,3])
 
# Creating histogram


plt.hist(salmon,bins = [2,4,6,8,10], 
         color = 'pink', edgecolor='black')
plt.hist(seabass,bins = [2,4,6,8,10],
         color = 'blue', edgecolor='black')

 # Adding extra features   
plt.ylabel("Number of Fish")
plt.xlabel("Lightness")
plt.title('Histogram of Lightness')
plt.legend(['Salmon','Seabass'])

# Show plot
plt.show()

def best_fit(X, Y):

    xbar = sum(X)/len(X)
    ybar = sum(Y)/len(Y)
    n = len(X) # or len(Y)

    numer = sum([xi*yi for xi,yi in zip(X, Y)]) - n * xbar * ybar
    denum = sum([xi**2 for xi in X]) - n * xbar**2

    b = numer / denum
    a = ybar - b * xbar

    print('best fit line:\ny = {:.2f} + {:.2f}x'.format(a, b))

    return a, b

seabass_x=np.array([8,9,5,7,3])
seabass_y=np.array([20,17,16,15,17])
salmon_x=np.array([3,4,5,6,7])
salmon_y=np.array([21,20,19,18,18])

size=np.array([100,100,100,100,100])



a, b = best_fit(salmon_x, salmon_y)
#best fit line:
#y = 0.80 + 0.92x

# plot points and fit line
import matplotlib.pyplot as plt

yfit = [a + b * xi for xi in salmon_x]
plt.plot(salmon_x, yfit)



plt.scatter(seabass_x, seabass_y, s=size)

plt.scatter(salmon_x, salmon_y, color = 'hotpink', s=size)

plt.ylabel("Width")
plt.xlabel("Lightness")
plt.title('Width vs Lightness')
seabass_x, seabass_y,
salmon_x, salmon_y,
plt.legend(['Seabass','Salmon'],fancybox=True, framealpha=1, shadow=True, borderpad=1)
plt.show()

seabass_x=np.array([8,9,5,7,3])
seabass_y=np.array([20,17,16,15,17])
salmon_x=np.array([3,4,5,6,7])
salmon_y=np.array([21,20,19,18,18])

size=np.array([100,100,100,100,100])






plt.scatter(seabass_x, seabass_y, s=size)

plt.scatter(salmon_x, salmon_y, color = 'hotpink', s=size)
plt.axhline(y=18, color='r', linestyle='-')

plt.ylabel("Width")
plt.xlabel("Lightness")
plt.title('Width vs Lightness')
seabass_x, seabass_y,
salmon_x, salmon_y,
plt.legend(['Salmon', 'Seabass'],fancybox=True, framealpha=1, shadow=True, borderpad=1)
plt.show()